prenet:
  conv_kernel_size: 3
  dropout: 0.1

transformer:
  encoder_layer: 4
  encoder_head: 2
  encoder_hidden: 256
  decoder_layer: 4
  decoder_head: 2
  decoder_hidden: 256
  conv_filter_size: 1024
  conv_kernel_size: [9, 1]
  encoder_dropout: 0.1
  decoder_dropout: 0.1

melencoder:
  encoder_hidden: 128
  spectral_layer: 2
  temporal_layer: 2
  slf_attn_layer: 1
  slf_attn_head: 2
  conv_kernel_size: 5
  encoder_dropout: 0.1

variance_predictor:
  filter_size: 256
  kernel_size: 3
  dropout: 0.5

variance_embedding:
  kernel_size: 9

multi_speaker: True

max_seq_len: 1000

vocoder:
  model: "HiFi-GAN" # support 'HiFi-GAN', 'MelGAN'
  speaker: "universal" # support  'LJSpeech', 'universal'
