path:
  ckpt_path: "./output/ckpt/LibriTTS_meta_learner"
  log_path: "./output/log/LibriTTS_meta_learner"
  result_path: "./output/result/LibriTTS_meta_learner"
optimizer:
  batch_size: 16
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
  lr_disc: 0.00002
  alpha: 10
step:
  meta_learning_step: 120000
  total_step: 200000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 40000
